server:
    port: 8089 #服务端
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:  #配置gateway
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://J-CLOUD-CONSUMER
          predicates:
            - After=2021-09-30T21:11:46.662+08:00[Asia/Shanghai]
            - Path=/user/** # 断言，路径相匹配的进行路由
        - id: user_hello
          uri: lb://J-CLOUD-CONSUMER1
          predicates:
          - After=2021-09-30T21:11:46.662+08:00[Asia/Shanghai]
          - Path=/test/** #断言,路径相匹配的进行路由
      discovery:
        locator:
          enabled: true #默认为false,true：开启通过微服务名访问 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
        enabled: true # 是否开启网关
    sentinel:  # 配置sentinel
      transport:
        dashboard: localhost:8080
